# Generated by Django 4.2.21 on 2025-05-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='base_resume',
        ),
    ]
