# Generated by Django 4.2.20 on 2025-04-23 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('current_city', models.CharField(blank=True, max_length=100, null=True)),
                ('current_state', models.CharField(blank=True, max_length=100, null=True)),
                ('current_country', models.CharField(blank=True, max_length=100, null=True)),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('target_industries', models.JSONField(blank=True, default=list)),
                ('can_join_immediately', models.BooleanField(blank=True, null=True)),
                ('willing_to_relocate', models.BooleanField(blank=True, null=True)),
                ('base_summary', models.TextField(blank=True, null=True)),
                ('base_education_json', models.JSONField(blank=True, default=list)),
                ('base_languages_json', models.JSONField(blank=True, default=list)),
                ('base_certificates_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to='bio.bio')),
            ],
            options={
                'ordering': ['network'],
                'unique_together': {('bio', 'network')},
            },
        ),
    ]
