version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://gvamsi:1113@db:5432/resume_gen_db

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
      target: build-stage
    volumes:
      - ./website:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://backend:8000/api

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: resume_gen_db
      POSTGRES_USER: gvamsi # MUST EDIT and match values used elsewhere
      POSTGRES_PASSWORD: 1113 # MUST EDIT and match values used elsewhere
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gvamsi -d resume_gen_db"] # MUST EDIT USER
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
