# Generated by Django 4.2.21 on 2025-05-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='apply_link',
            field=models.URLField(blank=True, help_text='Direct link to apply for the job.', max_length=1024, null=True),
        ),
    ]
