# Generated by Django 4.2.21 on 2025-05-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposts', '0002_jobpost_apply_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='url',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='user',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='source_url',
            field=models.URLField(db_index=True, default='https://placeholder.com/job', help_text='The unique URL where this job posting was found.', max_length=1024, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='apply_link',
            field=models.URLField(blank=True, help_text='Direct link to apply for the job, if different from source_url.', max_length=1024, null=True),
        ),
    ]
