# Generated by Django 4.2.20 on 2025-04-23 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Resume', max_length=200)),
                ('is_base_resume', models.BooleanField(db_index=True, default=False)),
                ('source_job_description', models.TextField(blank=True, null=True)),
                ('source_job_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('source_company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('work', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_base_resume', '-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('is_base_resume', True)), fields=('user', 'is_base_resume'), name='unique_base_resume_per_user'),
        ),
    ]
