# Generated by Django 4.2.21 on 2025-05-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_associated_job_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='tracking_link',
            field=models.URLField(blank=True, help_text='Link to track the application status for this resume, if applicable.', max_length=1024, null=True),
        ),
    ]
