# backend/profiles/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    UserProfileView,
    ExperienceViewSet,
    EducationViewSet,
    SkillViewSet
)

# Create a router and register our viewsets with it.
# DefaultRouter automatically creates the URLs for list, create,
# retrieve, update, destroy
router = DefaultRouter()
router.register(r'experiences', ExperienceViewSet, basename='experience')
router.register(r'education', EducationViewSet, basename='education')
router.register(r'skills', SkillViewSet, basename='skill')
# Note: We don't register UserProfileView with the router
# because it's not a full ViewSet
# and we want a single specific URL for it (/api/profile/).

# The API URLs are now determined automatically by the router.
# Plus, we add the specific path for the main user profile view.
urlpatterns = [
    # URL for retrieving/updating the logged-in user's main profile
    path('profile/', UserProfileView.as_view(), name='user-profile'),
    # Include the URLs generated by the router
    # for Experience, Education, Skill
    path('', include(router.urls)),
    # This will create URLs like:
    # /api/experiences/
    # /api/experiences/{id}/
    # /api/education/
    # /api/education/{id}/
    # /api/skills/
    # /api/skills/{id}/
]
